if (!dir.exists('local')) dir.create('local')
.libPaths("./local")
# remotes::install_github('pbreheny/ncvreg@bootstrap')
remotes::install_github('pbreheny/ncvreg@research')
# remotes::install_github('lharris421/hdi@master')
